version: '3.8'

services:
  alfred-bot:
    build: .
    container_name: alfred-bot
    restart: always
    environment:
      - OPENROUTER_API_KEY =${OPENROUTER_API_KEY}
    volumes:
      - alfred_session:/app/alfred_session
      - chat_history:/app/chat_history

volumes:
  alfred_session:
  chat_history: